from subprocess import call

print("---")
call(["make", "-f", "Makefile1"])
print("---")
call(["java", "-jar", "HelloUser.jar"])
print("---")
call(["make", "-f", "Makefile1", "clean"])
print("---")
call(["make", "-f", "Makefile2"])
print("---")
call(["java", "-jar", "HelloUser.jar"])
print("---")
call(["make", "-f", "Makefile2", "clean"])
print("---")
call(["make", "-f", "Makefile3"])
print("---")
call(["java", "-jar", "Hello.jar"])
print("---")
call(["make", "-f", "Makefile3", "clean"])
print("---")
